export { default as Header } from './Header/Header'
export { default as Menu } from './Menu/Menu'
export { default as Slider } from './Slider/Slider'
export { default as News } from './News/News'
export { default as Disciplines } from './Disciplines/Disciplines'
export { default as Contacts } from './Contacts/Contacts'
export { default as Footer } from './Footer/Footer'
export { default as ModalBlock } from './ModalBlock/ModalBlock'
export { default as Сopyright} from './Сopyright/Сopyright'